kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: claimcompass/unleash-server
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      add_host: "registry.npmjs.org:104.16.21.35"